### ISSUE TITLE
execute method of commands should always return an int

### ISSUE THREAD

**Issue by Ruben-Winant** [phpro/phpro-mage2-module-translations#14]
Hi, while using the module's commans i encountered the following error:
```shell
There is an error in /app/vendor/symfony/console/Command/Command.php at line: 301
Return value of "Phpro\Translations\Console\Command\ImportFull\Interceptor::execute()" must be of the type int, "null" returned.
#0 /app/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\C
ommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /app/vendor/magento/framework/Interception/Interceptor.php(138): Phpro\Translations\Console\Command\ImportFull\Interceptor->___callParent('run', Array)
#2 /app/vendor/magento/framework/Interception/Interceptor.php(153): Phpro\Translations\Console\Command\ImportFull\Interceptor->Magento\Framework\Interception\{closure}(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symf
ony\Component\Console\Output\ConsoleOutput))
#3 /app/generated/code/Phpro/Translations/Console/Command/ImportFull/Interceptor.php(77): Phpro\Translations\Console\Command\ImportFull\Interceptor->___callPlugins('run', Array, Array)
#4 /app/vendor/symfony/console/Application.php(1040): Phpro\Translations\Console\Command\ImportFull\Interceptor->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))       
#5 /app/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Phpro\Translations\Console\Command\ImportFull\Interceptor), Object(Symfony\Component\Console\Input\ArgvInput), Object(
Symfony\Component\Console\Output\ConsoleOutput))
#6 /app/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /app/vendor/symfony/console/Application.php(171): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /app/bin/magento(23): Symfony\Component\Console\Application->run()
#9 {main}
``` 

This happens with all of the follwoing commands:
- Console/Command/Export.php
- Console/Command/GenerateFrontendTranslations.php
- Console/Command/Import.php
- Console/Command/ImportFull.php
- Console/Command/PrepareKeysCommand.php

**Comment by stefliekens** [comment]
Hi @Ruben-Winant, we will check this asap.

**Comment by BrentRobert** [comment]
Hi @Ruben-Winant,
This should be fixed with https://github.com/phpro/phpro-mage2-module-translations/pull/16
